# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AgriGuardian' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AgriGuardian
  pod 'Firebase'
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'GoogleSignIn'

  target 'AgriGuardianTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AgriGuardianUITests' do
    # Pods for testing
  end

end
